[package]
name = "vello_tree_datagrid"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hashbrown = { workspace = true }
vello = { workspace = true }
vello_composition = { path = "../composition" }
once_cell = { workspace = true }
