[package]
name = "vello_chart_diagnostics"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
web-time = { workspace = true }
heapless = "0.8"
