using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("VelloSharp")]
[assembly: InternalsVisibleTo("VelloSharp.Text")]
[assembly: InternalsVisibleTo("VelloSharp.Avalonia.Winit")]
[assembly: InternalsVisibleTo("VelloSharp.Avalonia.Vello")]
[assembly: InternalsVisibleTo("VelloSharp.Skia.Gpu")]
[assembly: InternalsVisibleTo("VelloSharp.Skia.Cpu")]
[assembly: InternalsVisibleTo("VelloSharp.Gpu")]
[assembly: InternalsVisibleTo("VelloSharp.Ffi.Gpu")]
[assembly: InternalsVisibleTo("VelloSharp.Ffi.Sparse")]
[assembly: InternalsVisibleTo("VelloSharp.Skia.Core")]
[assembly: InternalsVisibleTo("VelloSharp.HarfBuzzSharp")]
[assembly: InternalsVisibleTo("HarfBuzzSharp")]
[assembly: InternalsVisibleTo("VelloSharp.Skia.Gpu.Tests")]
[assembly: InternalsVisibleTo("VelloSharp.Avalonia.Browser")]
[assembly: InternalsVisibleTo("VelloSharp.WebAssembly")]
