name: Build and Pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  native-linux:
    name: Native Linux (${{ matrix.rid }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            rid: linux-x64
            artifact-name: native-linux-x64
            library: libvello_ffi.so
          - target: aarch64-unknown-linux-gnu
            rid: linux-arm64
            artifact-name: native-linux-arm64
            library: libvello_ffi.so
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install cross toolchain
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Build native artifact
        run: ./scripts/build-native-linux.sh ${{ matrix.target }} release ${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/runtimes/${{ matrix.rid }}
          if-no-files-found: error

  native-macos:
    name: Native macOS (${{ matrix.rid }})
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            rid: osx-x64
            artifact-name: native-macos-x64
            library: libvello_ffi.dylib
            sdk: ""
          - target: aarch64-apple-darwin
            rid: osx-arm64
            artifact-name: native-macos-arm64
            library: libvello_ffi.dylib
            sdk: ""
          - target: aarch64-apple-ios
            rid: ios-arm64
            artifact-name: native-ios-arm64
            library: libvello_ffi.a
            sdk: iphoneos
          - target: x86_64-apple-ios
            rid: iossimulator-x64
            artifact-name: native-iossimulator-x64
            library: libvello_ffi.a
            sdk: iphonesimulator
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Configure Apple SDK
        if: matrix.sdk != ''
        run: echo "SDKROOT=$(xcrun --sdk ${{ matrix.sdk }} --show-sdk-path)" >> $GITHUB_ENV

      - name: Build native artifact
        run: ./scripts/build-native-macos.sh ${{ matrix.target }} release '${{ matrix.sdk }}' '${{ matrix.rid }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/runtimes/${{ matrix.rid }}
          if-no-files-found: error

  native-android:
    name: Native Android (${{ matrix.rid }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            rid: android-arm64
            artifact-name: native-android-arm64
            library: libvello_ffi.so
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install Android NDK
        run: |
          sudo apt-get update && sudo apt-get install -y unzip wget
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip -O $RUNNER_TEMP/android-ndk.zip
          unzip -q $RUNNER_TEMP/android-ndk.zip -d $RUNNER_TEMP
          echo "ANDROID_NDK_HOME=$RUNNER_TEMP/android-ndk-r26d" >> $GITHUB_ENV
          echo "$RUNNER_TEMP/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Build native artifact
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: ./scripts/build-native-android.sh ${{ matrix.target }} release ${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/runtimes/${{ matrix.rid }}
          if-no-files-found: error

  native-wasm:
    name: Native WASM (${{ matrix.rid }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: wasm32-unknown-unknown
            rid: browser-wasm
            artifact-name: native-wasm
            library: vello_ffi.wasm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build native artifact
        run: ./scripts/build-native-wasm.sh ${{ matrix.target }} release ${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/runtimes/${{ matrix.rid }}
          if-no-files-found: error

  native-windows:
    name: Native Windows (${{ matrix.rid }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            rid: win-x64
            artifact-name: native-windows-x64
            library: vello_ffi.dll
          - target: aarch64-pc-windows-msvc
            rid: win-arm64
            artifact-name: native-windows-arm64
            library: vello_ffi.dll
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build native library
        run: cargo build -p vello_ffi --target ${{ matrix.target }} --release

      - name: Collect native artifact
        shell: pwsh
        run: |
          $outDir = "artifacts\runtimes\${{ matrix.rid }}\native"
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $library = "${{ matrix.library }}"
          Copy-Item -Path "target\${{ matrix.target }}\release\$library" -Destination $outDir -Force
          $pdb = [System.IO.Path]::ChangeExtension("target\${{ matrix.target }}\release\$library", ".pdb")
          if (Test-Path $pdb) {
            Copy-Item -Path $pdb -Destination $outDir -Force
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/runtimes/${{ matrix.rid }}
          if-no-files-found: error

  pack-native:
    name: Pack Native NuGets
    runs-on: ubuntu-latest
    needs:
      - native-linux
      - native-macos
      - native-android
      - native-wasm
      - native-windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download native artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: native-*
          path: artifacts
          merge-multiple: true

      - name: Normalize native artifact layout
        run: |
          set -eo pipefail
          if [ -d artifacts/artifacts ]; then
            shopt -s dotglob
            mv artifacts/artifacts/* artifacts/
            rmdir artifacts/artifacts
          fi
          ls -R artifacts

      - name: Pack native runtime packages
        run: |
          set -eo pipefail
          mkdir -p artifacts/nuget
          declare -A seen
          mapfile -d '' native_dirs < <(find artifacts -type d -name native -path '*/runtimes/*/native' -print0 | sort -zu)

          if [ ${#native_dirs[@]} -eq 0 ]; then
            echo "No native runtime directories found under artifacts/."
            exit 1
          fi

          for nativeDir in "${native_dirs[@]}"; do
            rid=$(basename "$(dirname "$nativeDir")")

            if [[ -n "${seen[$rid]}" ]]; then
              continue
            fi
            seen[$rid]=1

            project="packaging/VelloSharp.Native.${rid}/VelloSharp.Native.${rid}.csproj"
            if [ ! -f "$project" ]; then
              echo "Skipping $rid (no packaging project at $project)"
              continue
            fi

            echo "Packing native package for $rid from $nativeDir"
            dotnet pack "$project" \
              -c Release \
              -p:NativeAssetsDirectory="$nativeDir" \
              -p:PackageOutputPath=$PWD/artifacts/nuget
          done

          if compgen -G "artifacts/nuget/*.nupkg" > /dev/null; then
            echo "Native packages created:"
            ls artifacts/nuget
          else
            echo "No native packages were produced."
            exit 1
          fi

      - name: Upload native NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: native-nuget-packages
          path: artifacts/nuget
          if-no-files-found: error

  pack-managed:
    name: Pack NuGet
    runs-on: ubuntu-latest
    needs:
      - pack-native
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download native NuGet packages
        uses: actions/download-artifact@v4
        with:
          name: native-nuget-packages
          path: artifacts/nuget

      - name: List native NuGet packages
        run: ls -R artifacts/nuget

      - name: Build managed projects
        run: dotnet build VelloSharp.sln -c Release -p:VelloSkipNativeBuild=true

      - name: Add local native feed
        run: dotnet nuget add source "${{ github.workspace }}/artifacts/nuget" --name VelloNativeLocal

      - name: Pack VelloSharp
        run: >
          dotnet pack VelloSharp/VelloSharp.csproj
          -c Release
          -p:VelloSkipNativeBuild=true
          -p:VelloIncludeNativeAssets=false
          -p:VelloUseNativePackageDependencies=true
          -p:VelloRequireAllNativeAssets=false
          -p:RestoreAdditionalProjectSources=${{ github.workspace }}/artifacts/nuget

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/nuget
          if-no-files-found: error
